@echo off
REM Build script for Asio Echo Demo on Windows using MSVC cl.exe
REM This script compiles both server and client executables

echo ========================================
echo Building Asio Echo Demo (Windows MSVC)
echo ========================================
echo.

REM Check if cl.exe is available
where cl.exe >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: cl.exe not found in PATH
    echo Please run this script from "Developer Command Prompt for VS" or "Developer PowerShell for VS"
    echo.
    exit /b 1
)

REM Display compiler version
echo Compiler version:
cl.exe 2>&1 | findstr /C:"Microsoft (R) C/C++"
echo.

REM Set include path to Asio submodule
set ASIO_INCLUDE=..\..\third_party\asio\asio\include
set CXXFLAGS=/EHsc /std:c++17 /W3 /I%ASIO_INCLUDE% /D_WIN32_WINNT=0x0601

echo Compiling asio_echo_server.cpp...
cl.exe %CXXFLAGS% /Fe:asio_echo_server.exe asio_echo_server.cpp
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to compile asio_echo_server.cpp
    exit /b 1
)
echo.

echo Compiling asio_echo_client.cpp...
cl.exe %CXXFLAGS% /Fe:asio_echo_client.exe asio_echo_client.cpp
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to compile asio_echo_client.cpp
    exit /b 1
)
echo.

echo ========================================
echo Build successful!
echo Executables:
echo   - asio_echo_server.exe
echo   - asio_echo_client.exe
echo ========================================

REM Clean up intermediate files generated by cl.exe
del *.obj >nul 2>nul